@hostname = http://localhost:5000

get http://localhost:5000

###
get {{hostname}}


###
post {{hostname}}/api/users
Body:{
name:Brad,
email:brad@gmail,
password:123456
}    
 
###
post {{hostname}}/api/users/login
 